services:
  devfrontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "4000:4000"
    container_name: devfrontend
  nest:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: tfd-nest
    depends_on:
      - db
      - redis
    volumes:
      - ./devbackend/src:/app/src
      - ./devbackend/test:/app/test
      - ./devbackend/.env:/app/.env
      - ./devbackend/upload:/app/upload
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: tfd-nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 8080:8080
  db:
    image: postgres:12
    container_name: tfd-nest-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql
  redis:
    image: redis:5
    container_name: tfd-redis
    ports:
      - 6379:6379
volumes:
  postgresdata:

