FROM nginx:1.20.0-alpine

COPY ./devbackend/docker/entrypoint-nginx.sh /

RUN set -ex && \
	apk add --no-cache bash && \
	chmod +x /entrypoint-nginx.sh

COPY ./devbackend/docker/vhost.template /etc/nginx/conf.d/vhost.template

CMD ["/entrypoint-nginx.sh"]
